### ISSUE TITLE
Все поля - с маленькой буквы

### ISSUE THREAD

**Issue by coursar** [ArkhipovMarat/Burgers#5]
https://github.com/ArkhipovMarat/Burgers/blob/6b8addec9f8c79cda21ed82541421676ef607ee3/src/main/java/Burger.java#L3-L14

**Comment by ArkhipovMarat** [comment]
исправлено

**Comment by coursar** [comment]
Issue нужно закрывать сообщениями коммитов

**Comment by ArkhipovMarat** [comment]
принято
